Repository chainer/chainerrl, pull requests merged in 2019-04, with the labels that each got.

#429 Make sure the agent sees when episodes end
  chainerrl/experiments/evaluator.py
  tests/experiments_tests/test_evaluator.py
Labels: bug

#430 Precompute log probability in PPO
  chainerrl/agents/ppo.py
Labels: enhancement

#443 Add VectorStackFrame to reduce memory usage in train_dqn_batch_ale.py
  chainerrl/env.py
  chainerrl/wrappers/__init__.py
  chainerrl/wrappers/vector_frame_stack.py
  examples/ale/train_dqn_batch_ale.py
  tests/wrappers_tests/test_vector_frame_stack.py
Labels: bug

#445 make FrameStack follow original spaces
  chainerrl/wrappers/atari_wrappers.py
  tests/wrappers_tests/test_atari_wrappers.py
Labels: test
