Repository chainer/chainerrl, pull requests merged in 2019-10, with the labels that each got.

#556 Add documentation for Q-functions and some missing details in docstrings
  chainerrl/q_function.py
  chainerrl/q_functions/state_q_functions.py
  docs/q_functions.rst
  docs/reference.rst
Labels: documentation

#567 Fixes Categorical Double DQN Error.
  chainerrl/agents/categorical_double_dqn.py
Labels: bug

#558 Pass env_id to replay_buffer methods to fix batch training
  chainerrl/agents/soft_actor_critic.py
Labels: bug, prio:high
