Repository chainer/chainerrl, pull requests merged in 2019-06, with the labels that each got.

#465 Apply `noisy_net_sigma` parameter
  examples/ale/train_dqn_ale.py
  examples/ale/train_dqn_batch_ale.py
  examples/atari/rainbow/train_rainbow.py
  examples/gym/train_dqn_gym.py
Labels: example

#431 Recurrent PPO with a stateless recurrent model interface
  README.md
  chainerrl/agents/ppo.py
  chainerrl/links/__init__.py
  chainerrl/links/stateless_recurrent.py
  chainerrl/links/stateless_recurrent_branched.py
  chainerrl/links/stateless_recurrent_sequential.py
  chainerrl/wrappers/atari_wrappers.py
  docs/links.rst
  examples/ale/train_ppo_ale.py
  tests/agents_tests/test_ppo.py
  tests/links_tests/test_stateless_recurrent.py
  tests/links_tests/test_stateless_recurrent_branched.py
  tests/links_tests/test_stateless_recurrent_sequential.py
Labels: enhancement

#493 Use Python 3.6 for ipynb
  .travis.yml
Labels: test
